#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Console\Command\Command;
use Uberstead\Command\BaseCommand;
use Uberstead\Container\Container;
use Symfony\Component\Console\Event\ConsoleCommandEvent;
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Uberstead\Service\ConfigManagerService;
use Uberstead\Service\SiteManagerService;
use Uberstead\Service\ValidatorService;
use Symfony\Component\Console\Event\ConsoleTerminateEvent;

set_time_limit(0);
require_once "vendor/autoload.php";

/*
 * Setup Container
 */
$container = new Container();

$container['config_manager'] = new ConfigManagerService();
$container['config_manager']->setContainer($container);

$container['validator'] = new ValidatorService();
$container['validator']->setContainer($container);

$container['site_manager'] = new SiteManagerService();
$container['site_manager']->setContainer($container);

/*
 * Load Commands
 */
$finder = new Finder();
$commandFiles = $finder->files()
    ->name('*Command.php')
    ->notName('*BaseCommand.php')
    ->in('src')
;

/*
 * Setup event dispatcher
 */
$dispatcher = new EventDispatcher();
$dispatcher->addListener(ConsoleEvents::COMMAND, function (ConsoleCommandEvent $event) {
        $input = $event->getInput();
        $output = $event->getOutput();

        if (posix_getuid() != 0) {
            $output->writeln('This command needs access to /etc/hosts and /etc/exports. Please run as root (sudo).');
            die();
        }

        /** @var BaseCommand $command */
        $command = $event->getCommand();
        if ($command instanceof BaseCommand) {
            // Force settings update if the settingscommand is executed
            $forceUpdate = ($command->getName() === "uberstead:settings");

            // If checkConfig returns true (settings are updated), refresh vagrant
            if (true === $command->getContainer()->getConfigManager()->updateConfig($input, $output, $command->getHelperSet(), $forceUpdate)) {
                $command->queueVagrantReload();
                $command->queueVagrantProvision();
            }
        }
    });

$dispatcher->addListener(ConsoleEvents::TERMINATE, function (ConsoleTerminateEvent $event) {
        /** @var BaseCommand $command */
        $command = $event->getCommand();
        $output = $event->getOutput();

        if ($command instanceof BaseCommand) {
            if ($command->isQueueVagrantProvision()) {
                $command->vagrantProvision($output);
            }
            if ($command->isQueueVagrantReload()) {
                $command->vagrantReload($output);
            }
            if ($command->getCommandForTerminateEvent() !== null) {
                exec($command->getCommandForTerminateEvent());
            }
        }
    });


$commands = array();
foreach ($commandFiles as $file) {
    if (preg_match('#^namespace\s+(.+?);.*class\s+(\w+).+;$#sm', $file->getContents(), $m)) {
        $class = $m[1].'\\'.$m[2];
        $object = new $class();
        if ($object instanceof Command) {
            $commands[] = $object;
            if (method_exists($object, 'setContainer')) {
                $object->setContainer($container);
            }
        }
    }
}

//---------------------------
// Run Application
//---------------------------
$console = new Application();
$console->setDispatcher($dispatcher);
$console->addCommands($commands);
$console->run();
